export const curatedProviders = [
  {
    id: "openai",
    name: "OpenAI / Codex",
    envVars: ["OPENAI_API_KEY"],
    rank: 1,
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    envVars: ["ANTHROPIC_API_KEY"],
    rank: 2,
  },
  {
    id: "google",
    name: "Google Gemini",
    envVars: ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
    rank: 3,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    envVars: ["DEEPSEEK_API_KEY"],
    rank: 4,
  },
  {
    id: "xai",
    name: "xAI Grok",
    envVars: ["XAI_API_KEY"],
    rank: 5,
  },
  {
    id: "mistral",
    name: "Mistral AI",
    envVars: ["MISTRAL_API_KEY"],
    rank: 6,
  },
  {
    id: "cohere",
    name: "Cohere",
    envVars: ["COHERE_API_KEY"],
    rank: 7,
  },
  {
    id: "meta",
    name: "Meta Llama",
    envVars: ["META_API_KEY", "LLAMA_API_KEY"],
    rank: 8,
  },
  {
    id: "alibaba",
    name: "Alibaba Qwen / DashScope",
    envVars: ["DASHSCOPE_API_KEY"],
    rank: 9,
  },
  {
    id: "baidu",
    name: "Baidu ERNIE / Qianfan",
    envVars: ["QIANFAN_ACCESS_KEY", "QIANFAN_SECRET_KEY"],
    rank: 10,
  },
  {
    id: "moonshot",
    name: "Moonshot / Kimi",
    envVars: ["MOONSHOT_API_KEY"],
    rank: 11,
  },
  {
    id: "zhipu",
    name: "Zhipu AI / GLM",
    envVars: ["ZHIPUAI_API_KEY"],
    rank: 12,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    envVars: ["OPENROUTER_API_KEY"],
    rank: 13,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    envVars: ["PERPLEXITY_API_KEY", "PPLX_API_KEY"],
    rank: 14,
  },
  {
    id: "together",
    name: "Together AI",
    envVars: ["TOGETHER_API_KEY"],
    rank: 15,
  },
  {
    id: "groq",
    name: "Groq",
    envVars: ["GROQ_API_KEY"],
    rank: 16,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    envVars: ["FIREWORKS_API_KEY"],
    rank: 17,
  },
  {
    id: "replicate",
    name: "Replicate",
    envVars: ["REPLICATE_API_TOKEN", "REPLICATE_API_KEY"],
    rank: 18,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    envVars: ["HUGGINGFACE_API_KEY", "HF_TOKEN", "HUGGING_FACE_HUB_TOKEN"],
    rank: 19,
  },
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    envVars: ["AZURE_OPENAI_API_KEY", "AZURE_OPENAI_ENDPOINT"],
    rank: 20,
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"],
    rank: 21,
  },
  {
    id: "vertex-ai",
    name: "Google Vertex AI",
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_CLOUD_PROJECT"],
    rank: 22,
  },
  {
    id: "ibm-watsonx",
    name: "IBM watsonx.ai",
    envVars: ["WATSONX_API_KEY", "IBM_CLOUD_API_KEY", "WATSONX_PROJECT_ID"],
    rank: 23,
  },
  {
    id: "nvidia",
    name: "NVIDIA AI",
    envVars: ["NVIDIA_API_KEY", "NVIDIA_NIM_API_KEY"],
    rank: 24,
  },
  {
    id: "cerebras",
    name: "Cerebras",
    envVars: ["CEREBRAS_API_KEY"],
    rank: 25,
  },
  {
    id: "sambanova",
    name: "SambaNova",
    envVars: ["SAMBANOVA_API_KEY"],
    rank: 26,
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    envVars: ["AI21_API_KEY"],
    rank: 27,
  },
  {
    id: "voyage",
    name: "Voyage AI",
    envVars: ["VOYAGE_API_KEY"],
    rank: 28,
  },
  {
    id: "jina",
    name: "Jina AI",
    envVars: ["JINA_API_KEY"],
    rank: 29,
  },
  {
    id: "aleph-alpha",
    name: "Aleph Alpha",
    envVars: ["ALEPH_ALPHA_API_KEY"],
    rank: 30,
  },
  {
    id: "anyscale",
    name: "Anyscale",
    envVars: ["ANYSCALE_API_KEY"],
    rank: 31,
  },
  {
    id: "octoai",
    name: "OctoAI",
    envVars: ["OCTOAI_TOKEN", "OCTOAI_API_KEY"],
    rank: 32,
  },
  {
    id: "baseten",
    name: "Baseten",
    envVars: ["BASETEN_API_KEY"],
    rank: 33,
  },
  {
    id: "modal",
    name: "Modal",
    envVars: ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
    rank: 34,
  },
  {
    id: "fal",
    name: "fal.ai",
    envVars: ["FAL_KEY"],
    rank: 35,
  },
  {
    id: "stability",
    name: "Stability AI",
    envVars: ["STABILITY_API_KEY"],
    rank: 36,
  },
  {
    id: "runway",
    name: "Runway",
    envVars: ["RUNWAY_API_KEY", "RUNWAYML_API_SECRET"],
    rank: 37,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    envVars: ["ELEVENLABS_API_KEY"],
    rank: 38,
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    envVars: ["ASSEMBLYAI_API_KEY"],
    rank: 39,
  },
  {
    id: "deepgram",
    name: "Deepgram",
    envVars: ["DEEPGRAM_API_KEY"],
    rank: 40,
  },
  {
    id: "rev-ai",
    name: "Rev AI",
    envVars: ["REVAI_ACCESS_TOKEN", "REV_AI_API_KEY"],
    rank: 41,
  },
  {
    id: "pinecone",
    name: "Pinecone",
    envVars: ["PINECONE_API_KEY"],
    rank: 42,
  },
  {
    id: "weaviate",
    name: "Weaviate",
    envVars: ["WEAVIATE_API_KEY", "WEAVIATE_URL"],
    rank: 43,
  },
  {
    id: "qdrant",
    name: "Qdrant",
    envVars: ["QDRANT_API_KEY", "QDRANT_URL"],
    rank: 44,
  },
  {
    id: "milvus",
    name: "Zilliz / Milvus",
    envVars: ["ZILLIZ_API_KEY", "MILVUS_URI", "MILVUS_TOKEN"],
    rank: 45,
  },
  {
    id: "supabase",
    name: "Supabase Vector",
    envVars: ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_ANON_KEY"],
    rank: 46,
  },
  {
    id: "upstash",
    name: "Upstash Vector",
    envVars: ["UPSTASH_VECTOR_REST_URL", "UPSTASH_VECTOR_REST_TOKEN"],
    rank: 47,
  },
  {
    id: "langsmith",
    name: "LangSmith",
    envVars: ["LANGSMITH_API_KEY", "LANGCHAIN_API_KEY"],
    rank: 48,
  },
  {
    id: "llamaindex",
    name: "LlamaIndex Cloud",
    envVars: ["LLAMA_CLOUD_API_KEY"],
    rank: 49,
  },
  {
    id: "portkey",
    name: "Portkey",
    envVars: ["PORTKEY_API_KEY"],
    rank: 50,
  },
];
